---

name: packer-kali-virtualbox

on:
  #schedule:
  #  - cron: '15 02 * * 0'
  push:
    paths:
      - '.github/workflows/packer-kali-virtualbox.yml'
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # install virtualbox
      - name: Install Virtualbox
        run: |
          sudo apt update -y
          sudo apt-get install -y git bash openssl curl zip linux-headers-generic
          sudo add-apt-repository multiverse 
          curl https://download.virtualbox.org/virtualbox/6.1.34/virtualbox-6.1_6.1.34-150636.1~Ubuntu~eoan_amd64.deb --output virtualbox-6.1_6.1.34-150636.1~Ubuntu~eoan_amd64.deb
          sudo apt install -y libqt5core5a libqt5gui5 libqt5opengl5 libqt5printsupport5 libqt5widgets5 libqt5x11extras5 libsdl1.2debian libopus0 virtualbox-guest-x11
          sudo dpkg -i ./virtualbox-6.1_6.1.34-150636.1~Ubuntu~eoan_amd64.deb
          sudo apt-get update -y
          curl https://download.virtualbox.org/virtualbox/6.1.34/Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack --output Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack
          echo "y" | sudo vboxmanage extpack install ./Oracle_VM_VirtualBox_Extension_Pack-6.1.34.vbox-extpack
#          sudo apt install -y virtualbox
#          sudo dpkg-reconfigure virtualbox-dkms
#          sudo apt update -y
#          sudo apt install virtualbox-ext-pack

      # install packer
      - name: Install Packer
        run: |
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get -y install packer
          sudo dpkg-reconfigure packer
          sudo ldconfig

      # fix backwards incompatibilities in template
#      - name: Fix Template
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: fix
#          target: templates/kali.json

      # validate templates
 #     - name: Validate Template
 #       uses: hashicorp/packer-github-actions@master
 #       with:
 #         command: validate
 #         arguments: -syntax-only
 #         target: templates/kali.json

       # build artifact
#      - name: Build Artifact
#        uses: hashicorp/packer-github-actions@master

#        with:
#          command: build
#          arguments: |
#            -color=false
#            -on-error=abort
#            -only=virtualbox-iso
#            -var iso_url=https://cdimage.kali.org/kali-images/kali-weekly/kali-linux-2022-W16-installer-amd64.iso
#            -var iso_checksum=eface812076f925f59c448596894b11075bf40212752f704ad333998c9c28d9f
#            -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }}
#            -var account_key=${{ secrets.VAGRANTCLOUD_API }}
#            -var box_version=1.0.0
#            -var metadata=include/vagrant/metadta/virtualbox/metadata.json
#            -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile
#          target: templates/kali.json
#        env:
#          PACKER_LOG: 1

      # download iso
      - name: Download ISO
        run: |
          curl http://cdimage.kali.org/kali-images/kali-weekly/ |grep -oE 'kali-linux-[0-9]{1,4}-W[0-9]{1,2}-installer-amd64.iso'| head -n 1 > target_iso.lst
          curl -L http://cdimage.kali.org/kali-images/kali-weekly/$(cat target_iso.lst) --output $(cat target_iso.lst)
          file $(cat target_iso.lst)
          sudo apt -y install coreutils
  
      # fix backwards incompatibilities in template
      - name: Fix Template
        run: sudo packer fix templates/kali.json

      # validate templates
      - name: Validate Template
        run: |
          sudo packer validate -only=virtualbox-iso -var iso_url=$(cat target_iso.lst) -var iso_checksum=$(sha256sum $(cat target_iso.lst) | cut -d " " -f 1) -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }} -var account_key=${{ secrets.VAGRANTCLOUD_API }} -var box_version=1.0.0 -var metadata=include/vagrant/metadta/virtualbox/metadata.json -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile templates/kali.json

      # build artifact
      - name: Build Artifact
        run: |
          sudo PACKER_LOG=1 packer build -color=false -on-error=abort -only=virtualbox-iso -var iso_url=$(cat target_iso.lst) -var iso_checksum=$(sha256sum $(cat target_iso.lst) | cut -d " " -f 1) -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }} -var account_key=${{ secrets.VAGRANTCLOUD_API }} -var box_version=1.0.0 -var metadata=include/vagrant/metadta/virtualbox/metadata.json -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile templates/kali.json

      # additional steps to process artifacts
