---

name: packer-kali-virtualbox

on:
  #schedule:
  #  - cron: '15 02 * * 0'
  push:
    paths:
      - '.github/workflows/packer-kali-virtualbox.yml'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: templates/kali.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: templates/kali.json

      # create environment variable of latest kali image
      - name: Get latest kali image
        run: |
          echo ISO_URL=http://cdimage.kali.org/kali-images/kali-weekly/$( \
            curl http://cdimage.kali.org/kali-images/kali-weekly/ \
            |grep -oE 'kali-linux-[0-9]{1,4}-W[0-9]{1,2}-installer-amd64.iso' \
            | head -n 1 ) >> $GITHUB_ENV

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: |
            -color=false -on-error=abort -only=virtualbox-iso -var iso_url=$ISO_URL -var iso_checksum=file:https://mirror.lagoon.nc/kali-images/kali-weekly/SHA256SUMS -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }} -var account_key=${{ secrets.VAGRANTCLOUD_API }} -var box_version=1.0.0 -var metadata=include/vagrant/metadta/virtualbox/metadata.json -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile
          target: templates/kali.json
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
  
