---

name: packer-kali-virtualbox

on:
  schedule:
    - cron: '5 6 * * 6'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: templates/kali.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: templates/kali.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: |
            -color=false
            -on-error=abort
            -only=virtualbox-iso
            -var iso_url=ISO_URL
            -var iso_checksum=ISO_CHECKSUM
            -var account_name=ACCOUNT_NAME
            -var account_key=ACCOUNT_KEY
            -var box_version=BOX_VERSION
            -var metadata=METADATA
            -var vagrantfile=VAGRANTFILE
          target: templates/kali.json
        env:
          PACKER_LOG: 1
          ACCOUNT_NAME: ${{ secrets.vagrantcloud_username }}
          ACCOUNT_KEY: ${{ secrets.vagrantcloud_api }}
          BOX_VERSION: "1.0.0"
          ISO_URL: "https://cdimage.kali.org/kali-images/kali-weekly/kali-linux-2022-W16-installer-amd64.iso"
          ISO_CHECKSUM: "EFACE812076F925F59C448596894B11075BF40212752F704AD333998C9C28D9F"
          METADATA: "include/vagrant/metadta/virtualbox/metadata.json"
          VAGRANTFILE: "include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile"

      # additional steps to process artifacts
