---

name: packer-kali-virtualbox

on:
  schedule:
    - cron: '41 11 * * 5'
  paths:
    - templates/kali.json

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: templates/kali.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: templates/kali.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -only=virtualbox-iso"
          target: templates/kali.json
        env:
          PACKER_LOG: 1
          account_name: ${{ secrets.vagrantcloud_username }}
          account_key: ${{ secrets.vagrantcloud_api }}
          box_version: "1.0.0"
          iso_url: "https://cdimage.kali.org/kali-images/kali-weekly/kali-linux-2022-W16-installer-amd64.iso"
          iso_checksum: "eface812076f925f59c448596894b11075bf40212752f704ad333998c9c28d9f"
          metadata: "include/vagrant/metadta/virtualbox/metadata.json"
          vagrantfile: "include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile"

      # additional steps to process artifacts
