---

name: packer-kali-virtualbox

on:
  #schedule:
  #  - cron: '15 02 * * 0'
  push:
    paths:
      - '.github/workflows/packer-kali-virtualbox.yml'
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # install virtualbox
      - name: Install Virtualbox
        run: |
          sudo apt update -y
          sudo apt-get install -y git bash openssl curl zip 
          sudo add-apt-repository multiverse 
          sudo apt-get update -y
          sudo apt install -y virtualbox linux-headers-generic
          sudo dpkg-reconfigure virtualbox-dkms
          sudo ldconfig

      # install packer
      - name: Install Packer
        run: |
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get -y install packer
          sudo dpkg-reconfigure packer
          sudo ldconfig

      # fix backwards incompatibilities in template
#      - name: Fix Template
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: fix
#          target: templates/kali.json

      # validate templates
 #     - name: Validate Template
 #       uses: hashicorp/packer-github-actions@master
 #       with:
 #         command: validate
 #         arguments: -syntax-only
 #         target: templates/kali.json

       # build artifact
#      - name: Build Artifact
#        uses: hashicorp/packer-github-actions@master

#        with:
#          command: build
#          arguments: |
#            -color=false
#            -on-error=abort
#            -only=virtualbox-iso
#            -var iso_url=https://cdimage.kali.org/kali-images/kali-weekly/kali-linux-2022-W16-installer-amd64.iso
#            -var iso_checksum=eface812076f925f59c448596894b11075bf40212752f704ad333998c9c28d9f
#            -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }}
#            -var account_key=${{ secrets.VAGRANTCLOUD_API }}
#            -var box_version=1.0.0
#            -var metadata=include/vagrant/metadta/virtualbox/metadata.json
#            -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile
#          target: templates/kali.json
#        env:
#          PACKER_LOG: 1

      # download iso
      - name: Download ISO
        run: |
          curl https://cdimage.kali.org/kali-images/kali-weekly/kali-linux-2022-W16-installer-amd64.iso --output kali-linux-2022-W16-installer-amd64.iso
          sudo apt -y install sha265sum
          export ISO_CHECKSUM=$(sha256sum kali-linux-2022-W16-installer-amd64.iso)
  
      # fix backwards incompatibilities in template
      - name: Fix Template
        run: sudo packer fix templates/kali.json

      # validate templates
      - name: Validate Template
        run: sudo packer validate -only=virtualbox-iso -var iso_url=kali-linux-2022-W16-installer-amd64.iso -var iso_checksum=ISO_CHECKSUM -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }} -var account_key=${{ secrets.VAGRANTCLOUD_API }} -var box_version=1.0.0 -var metadata=include/vagrant/metadta/virtualbox/metadata.json -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile templates/kali.json

      # build artifact
      - name: Build Artifact
        run: sudo packer build -color=false -on-error=abort -only=virtualbox-iso -var iso_url=kali-linux-2022-W16-installer-amd64.iso -var iso_checksum=ISO_CHECKSUM -var account_name=${{ secrets.VAGRANTCLOUD_USERNAME }} -var account_key=${{ secrets.VAGRANTCLOUD_API }} -var box_version=1.0.0 -var metadata=include/vagrant/metadta/virtualbox/metadata.json -var vagrantfile=include/vagrant/Vagrantfile/virtualbox/linux/Vagrantfile templates/kali.json
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
